### PR TITLE
Add Splinter logo files

### PR DESCRIPTION
**Pull request by davececchi**
Final JPG versions of new Splinter logos.

Signed-off-by: David Cecchi <David_Cecchi@cargill.com>

### CODE REVIEW

**Comment by peterschwarz** [comment]
Why is the non-gradient version of the logo with the text "magenta" and the non-gradient version of just the logo "fuchsia"?

**Comment by RyanLassigBanks** [comment]
I like the pink

**Comment by ltseeley** [comment]
Typo in filename: "Splinter_Logos_Lgootype - Black.jpg"

**Comment by jsmitchell** [comment]
I'd recommend lossless vector (svg) and lossless raster (png) versions instead of jpg.

**Comment by davececchi** [comment]
I'm directing designer here so I can try and minimize ongoing telephone stuff.

**Comment by davececchi** [comment]
Designer is monitoring this thread just fyi

**Comment by jsmitchell** [comment]
No spaces or capital letters in filenames, please.

**Comment by vaporos** [comment]
Not sure we need png in the repo, maybe over in the docs repo where we don't care as much about repo size.

**Comment by davececchi** [comment]
All changes addressed.  Provided SVG and PNG.

**Comment by jsmitchell** [comment]
These PNG versions are very small (image dimension wise). We'll need much higher print-res versions for the documentation repository (or wherever the high res renderings will be stored.)

**Comment by vaporos** [comment]
Let's either check in only the svg files here, or only the single svg file we need for the README.md file, and check in the rest into splinter-docs.

**Comment by vaporos** [comment]
This was moved to https://github.com/Cargill/splinter-docs/pull/38

**Pull request closed without merging**
