### PR TITLE
Fix modify users deserialization bug

### PR DESCRIPTION
**Pull request by RyanLassigBanks**
Fixes bug that caused `PUT /biome/users/{id}` to not properly
deserialize. This also refactors the route so that we're only
deserializing the payload once instead of three times. Additionally
this PR adds password salting to modify users routes

Signed-off-by: Ryan Banks <rbanks@bitwise.io>

### CODE REVIEW

**Comment by dnewh** [comment]
tested

**Comment by peterschwarz** [comment]
How can one test this?

**Comment by RyanLassigBanks** [comment]
> How can one test this? The code looks fine, otherwise

I've been testing using the docker file in grid.

1) Checkout PR
2) clone grid
3) Edit the grid on splinter [docker file](https://github.com/hyperledger/grid/blob/cd5e8b5cfae46bb60cd44bba78373bdcce932201/examples/splinter/docker-compose.yaml#L160) to point to local splinter branch
```
splinterd-alpha:
    image: splinterd-grid
    build:
      context: ../../../splinter
      dockerfile: splinterd/Dockerfile-installed-bionic
      args:
        - CARGO_ARGS=${CARGO_ARGS}
        - REPO_VERSION=${REPO_VERSION}
    container_name: splinterd-alpha
    hostname: splinterd-alpha
```
4) set experimental flags and up the docker-compose
5) Once it's spun up test it using curl or postman

Create user `POST /biome/register`
Log in `POST /biome/login`
Change password `PUT /biome/users/{user_id}`
Attempt to log in again to verify that password was successfully changed.

**Comment by peterschwarz** [comment]
Tested with the following:

1. Set `export 'CARGO_ARGS=-- --features experimental'`
2. run  `docker-compose up --build`
3. Import the following requests to postman (provided by @RyanLassigBanks )
```json
{
	"info": {
		"_postman_id": "ec7a8298-6cdf-48af-b542-139ff0fe4687",
		"name": "Biome Login",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "localhost:8080/biome/register",
			"event": [
				{
					"listen": "prerequest",
					"script": {
						"id": "3c9782fb-b55a-48e4-b982-c819621923ea",
						"exec": [
							""
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"value": "application/javascript",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"username\": \"test@test1.com\",\n\t\"hashed_password\": \"Admin2193!\"\n}",
					"options": {
						"raw": {
							"language": "javascript"
						}
					}
				},
				"url": {
					"raw": "localhost:8080/biome/register",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"biome",
						"register"
					]
				}
			},
			"response": []
		},
		{
			"name": "http://localhost:8080/biome/login",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"value": "application/javascript",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"username\": \"test@test1.com\",\n\t\"hashed_password\": \"Admin2193!\"\n}",
					"options": {
						"raw": {
							"language": "javascript"
						}
					}
				},
				"url": {
					"raw": "http://localhost:8085/biome/login",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8085",
					"path": [
						"biome",
						"login"
					]
				}
			},
			"response": []
		},
		{
			"name": "http://localhost:8080/biome/users/c7ec9218-598a-4eb5-b7f2-185b39389991",
			"request": {
				"method": "PUT",
				"header": [
					{
						"key": "Authorization",
						"value": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYzdlYzkyMTgtNTk4YS00ZWI1LWI3ZjItMTg1YjM5Mzg5OTkxIiwiaXNzIjoic2VsZi1pc3N1ZWQiLCJleHAiOjE1ODYyNzgyODV9.7aebk0D8bYbZF5-G7HGHHhRRY5Q8Lzv-n2e9awhV1qk",
						"type": "text"
					},
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"value": "application/json",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"username\": \"test@test1.com\",\n    \"hashed_password\": \"Admin2193!\",\n    \"new_password\": \"hello\",\n    \"new_key_pairs\": [\n        {\n            \"display_name\": \"test\",\n            \"encrypted_private_key\": \"{\\\"iv\\\":\\\"4+8Q6tTdt8cyH7ZLd0vJdA==\\\",\\\"v\\\":1,\\\"iter\\\":10000,\\\"ks\\\":128,\\\"ts\\\":64,\\\"mode\\\":\\\"ccm\\\",\\\"adata\\\":\\\"\\\",\\\"cipher\\\":\\\"aes\\\",\\\"salt\\\":\\\"HH/r6mr5Ils=\\\",\\\"ct\\\":\\\"uG8WbDJUz/wRMPHB9Ynm4oYrxuPo9PbD8trnwx5AF25on2lcknLtG4tMrq38mtc8VS5Za2F6p5ZkQm2njZcuayUYD6q5HUNL\\\"}\",\n            \"public_key\": \"03aa1114f0c47e834fbed9a2724d7c18c96231a5e5752c31c9167d6e199c6db76e\"\n        },\n        {\n            \"display_name\": \"t2\",\n            \"encrypted_private_key\": \"{\\\"iv\\\":\\\"50EWdJ7TMdWhElqYMgaCvg==\\\",\\\"v\\\":1,\\\"iter\\\":10000,\\\"ks\\\":128,\\\"ts\\\":64,\\\"mode\\\":\\\"ccm\\\",\\\"adata\\\":\\\"\\\",\\\"cipher\\\":\\\"aes\\\",\\\"salt\\\":\\\"HH/r6mr5Ils=\\\",\\\"ct\\\":\\\"RmzLq7gd+Ydb2QlwRuDxEX5JTiOyNTZHvBG4Up/w/BTyJnmTkJbvrDS8EM/T/2SjFcSJbRCrKIX0xgV73P7m+J6J4OCjHDKa\\\"}\",\n            \"public_key\": \"03b115b4fcca37e6d1f90bc6b2818352498936bbab28b17de7b12060a278c418af\"\n        }\n    ]\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "http://localhost:8080/biome/users/c7ec9218-598a-4eb5-b7f2-185b39389991",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"biome",
						"users",
						"c7ec9218-598a-4eb5-b7f2-185b39389991"
					]
				}
			},
			"response": []
		},
		{
			"name": "http://localhost:8080/biome/login",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"value": "application/javascript",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"username\": \"test@test1.com\",\n\t\"hashed_password\": \"hello\"\n}",
					"options": {
						"raw": {
							"language": "javascript"
						}
					}
				},
				"url": {
					"raw": "http://localhost:8080/biome/login",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"biome",
						"login"
					]
				}
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}
``` 
4. Run each request in order, but replace the provided user id with the results of the register request and the Authorization header with the `token` value returned.

**Pull request merged**
